In [1]:
!pip install numpy

In [ ]:
# Array

In [4]:
import numpy as np
array_one = np.array((3,5))
array_one

array([3, 5])

In [5]:
numbers= [9,6,8,7]
array_two = np.array(numbers)
array_two

array([9, 6, 8, 7])

In [ ]:
# array of zeros

In [11]:
array_zeros = np.zeros((5,7))
array_zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# array of ones

In [13]:
array_of_ones = np.ones((2,3))
array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#dtype()

In [14]:
array_of_ones = np.ones((2,3),dtype= np.int16)
array_of_ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [ ]:
#array of empty

In [47]:
array_empty = np.empty((3,4))
array_empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# eye identity

In [24]:
array_eye = np.eye(8)
array_eye

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# arrange

In [36]:
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
array_of_odds = np.arange(1,30,2)
array_of_odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])