In [ ]:
# Universal Functions

In [1]:
import numpy as np

In [3]:
angles = np.array([0,30,45,60,90])
angles

array([ 0, 30, 45, 60, 90])

In [5]:
angles_radians=angles*np.pi/180
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [7]:
print('Sin of angles in the array:')
print(np.sin(angles_radians))

Sin of angles in the array:
[0.         0.5        0.70710678 0.8660254  1.        ]


In [8]:
print('Cosine of angles in the array:')
print(np.cos(angles_radians))

Cosine of angles in the array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [9]:
print('Tanget of angles in the array:')
print(np.tan(angles_radians))

Tanget of angles in the array:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [11]:
angles_radians =np.radians(angles)
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [ ]:
# Arcsin, arcos, arctan ----> inverse the trigonometric functions

In [14]:
sin = np.sin(angles*np.pi/180)
print('Compute sin inverse of angles. Returned values are in radian')
inv = np.arcsin(sin)
print(inv)

Compute sin inverse of angles. Returned values are in radian
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [ ]:
# Convert radian to degrees

In [18]:
print('Check result by conversting radian to degrees:')
print(np.degrees(inv))

Check result by conversting radian to degrees:
[ 0. 30. 45. 60. 90.]


In [ ]:
# Statistical Funtions

In [20]:
test_scores = np.array([32.32,38.80,42.01,34.54,45.61])
print('Mean of test scores of students')
print(np.mean(test_scores))

Mean of test scores of students
38.65599999999999


In [ ]:
# Exporting dataset

In [38]:
salaries = np.genfromtxt('C:\\Users\\backup2\\Desktop\\Practise Dataset py\\salary.csv', delimiter=',')
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [40]:
salaries.shape

(1147,)

In [51]:
Mean = np.mean(salaries)
Median =np.median(salaries)
Standard_deviation = np.std(salaries)
Variance= np.var(salaries)
print(f"Mean of Salaries: {Mean}")
print(f"Median of Salaries: {Median}")
print(f"Standard deviation of Salaries: {Standard_deviation}")
print(f"Variance of Salaries: {Variance}")

Mean of Salaries: 55894.53879686138
Median of Salaries: 48000.0
Standard deviation of Salaries: 55170.37550939316
Variance of Salaries: 3043770333.8474483


In [ ]:
# other approach = %

In [54]:
print('Mean=%i' %Mean)
print('Median=%i' %Median)
print('Standard deviation=%i' %Standard_deviation)
print('Variance=%i' %Variance)

Mean=55894
Median=48000
Standard deviation=55170
Variance=3043770333
