In [ ]:
# Iterating

In [1]:
import numpy as np

In [2]:
a = np.arange(11)**2 #......................... 1D Array
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [3]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [ ]:
# Multi Dimensonal Array

In [4]:
students= np.array([['A','B','C','D'],[65,71,98,82],[71,65,89,90]])

In [8]:
for x in students:
    print('x =',x)

x = ['A' 'B' 'C' 'D']
x = ['65' '71' '98' '82']
x = ['71' '65' '89' '90']


In [ ]:
# Flatten a multi dimensional array

In [9]:
for x in students.flatten():
    print(x)

A
B
C
D
65
71
98
82
71
65
89
90


In [ ]:
# Fortran order :

In [17]:
for x in students.flatten(order='F'):
    print(x)

A
65
71
B
71
65
C
98
89
D
82
90


In [ ]:
# nditer----------------> alternatve approach of flatten. Its sepcifially designed for numpy library

In [19]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [21]:
for i in np.nditer(x,order='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [ ]:
# Flags

In [25]:
for i in np.nditer(x,order='F',flags=['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [ ]:
# Read write array

In [31]:
for arr in np.nditer(x):
    arr[...] = arr*arr

ValueError: assignment destination is read-only

In [44]:
for arr in np.nditer(x,op_flags=['readwrite']):
    arr[...] = arr*arr
    print(x)

[[          0           1           0  1995565057]
 [          0   -59967487           0   684437505]
 [          0 -1876701183           0   -62236671]]
[[          0           1           0  1995565057]
 [          0   -59967487           0   684437505]
 [          0 -1876701183           0   -62236671]]
[[          0           1           0  1995565057]
 [          0   -59967487           0   684437505]
 [          0 -1876701183           0   -62236671]]
[[          0           1           0 -1876701183]
 [          0   -59967487           0   684437505]
 [          0 -1876701183           0   -62236671]]
[[          0           1           0 -1876701183]
 [          0   -59967487           0   684437505]
 [          0 -1876701183           0   -62236671]]
[[          0           1           0 -1876701183]
 [          0   689565697           0   684437505]
 [          0 -1876701183           0   -62236671]]
[[          0           1           0 -1876701183]
 [          0   689565697