In [ ]:
# 1D array

In [2]:
import numpy as np

In [5]:
array_1d = np.arange(6)
array_1d

array([0, 1, 2, 3, 4, 5])

In [ ]:
# 2D array

In [9]:
array_2d = np.array([(2,3),(4,5)])
array_2d

array([[2, 3],
       [4, 5]])

In [12]:
array_nd = np.arange(6).reshape(2,3)
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 3D array

In [15]:
array_3d= np.arange(24).reshape(2,3,4)
array_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
array_3d.shape

(2, 3, 4)

In [ ]:
# set_printoptions

In [20]:
np.set_printoptions(threshold=np.nan)
print(np.arange(6).reshape(2,3))

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

In [ ]:
# Arithmetic Operations

In [21]:
A = np.array([10,10,10])
B= np.array([5,5,5])

In [22]:
A+B

array([15, 15, 15])

In [23]:
A-B

array([5, 5, 5])

In [24]:
A*B

array([50, 50, 50])

In [25]:
A/B

array([2., 2., 2.])

In [27]:
A %3

array([1, 1, 1], dtype=int32)

In [28]:
A<35

array([ True,  True,  True])

In [29]:
B>30

array([False, False, False])

In [30]:
A**2

array([100, 100, 100], dtype=int32)

In [ ]:
# dot function

In [34]:
x = np.array([(1,2),(0,1)])
y = np.array([(2,0),(3,2)])
print('X:\n',x)
print('Y:\n',y)

X:
 [[1 2]
 [0 1]]
Y:
 [[2 0]
 [3 2]]


In [35]:
x*y

array([[2, 0],
       [0, 2]])

In [36]:
x.dot(y)

array([[8, 4],
       [3, 2]])

In [37]:
np.dot(x,y)

array([[8, 4],
       [3, 2]])

In [40]:
A*=3
A

array([30, 30, 30])

In [43]:
B+=A
B

array([35, 35, 35])

In [ ]:
# Unary Operators

In [46]:
ages = np.array([18,12,20])
ages.sum()

50

In [47]:
ages.min()

12

In [48]:
ages.max()

20